# Installing VSCode extensions

$schema: 1.0
name: powershell
description: Uses PowerShell to install VSCode extensions
author: MP
command: |
  $env:Path = [System.Environment]::GetEnvironmentVariable('Path','Machine') + ';' + [System.Environment]::GetEnvironmentVariable('Path','User') 
  code --install-extension github.copilot
  code --install-extension github.copilot-chat        
  code --install-extension GitHub.vscode-github-actions
  code --install-extension ms-vscode-remote.remote-wsl
  code --install-extension ms-vscode-remote.remote-containers
  code --install-extension ms-azuretools.azure-dev
  code --install-extension ms-azuretools.vscode-docker
  code --install-extension ms-dotnettools.csdevkit
  code --install-extension ms-dotnettools.dotnet-maui
